### ISSUE TITLE
Track how many times PostgreSQL has been restarted

### ISSUE THREAD

**Issue by sharmay** [CrunchyData/pgmonitor#118]
Also generate an alert

**Comment by keithf4** [comment]
Added in PR https://github.com/CrunchyData/pgmonitor/pull/156

This does not track how many times it's been restarted, just the time since the last restart(in seconds). Can then create an alert rule based on the time being less than a certain value since it will reset if it's ever restarted.

**Comment by keithf4** [comment]
If a restart count or trend is desired, a graph can be made of the time metric.
