### ISSUE TITLE
Track if postgresql settings have changed

### ISSUE THREAD

**Issue by sharmay** [CrunchyData/pgmonitor#119]
Also generate an Alert

**Comment by keithf4** [comment]
Simple reload monitoring may not be possible since that happening is only ever indicated in the logs. What may be better instead of this is configuration checksum monitoring.

**Comment by dtseiler** [comment]
Curious, what is the value of such a check?

**Comment by keithf4** [comment]
Only time a reload is ever done is to change config, so again, I think this is better done as a config checksum vs a reload monitor. Value of that is know if/when your configuration changes unexpectedly. The check_postgres tool for nagios comes with this by default and it's very handy.

**Comment by keithf4** [comment]
So not quite sure how to do this currently. I'm able to get a consistent md5 hash of the current settings using the following query
```
WITH ordered_list AS (
                SELECT name, setting FROM pg_settings ORDER BY name, setting)
            SELECT md5(string_agg(name||setting, ',')) AS hash FROM ordered_list;
```
However, prometheus doesn't really have a datatype that supports this as a value that we could alert on if it changed. While you can set a label to whatever you want, the values must be numeric.

https://prometheus.io/docs/concepts/metric_types/

**Comment by keithf4** [comment]
Actually thinking about this more and writing down so I don't forget...

- Create a table in `monitoring` schema to store both the md5 hash, the raw string, as well as a timestamp of when that hash was first collected
- Have metric call a function instead that will write to that table whenever the md5 hash changes
- Figure out some means of monitoring that table, using the same function call, to alert when a change is detected and also allow a way to reset things when change is confirmed to be good.

Having the raw settings string will allow comparison to see what changed. Also, only storing new data when it changes and not doing any updates/deletes avoids bloating a table needlessly.

**Comment by keithf4** [comment]
This has been added in PR https://github.com/CrunchyData/pgmonitor/pull/156
