### ISSUE TITLE
use =~ instead of = on jobname

### ISSUE THREAD

**Issue by hunleyd** [CrunchyData/pgmonitor#132]
As Keith and I discovered today, if the user enters something dumb like an IP address for the jobname, then the current overview dashboards break. Editing them and changing from `=` to`=~` wherever the jobname appears in a query resolves it. 

According to the docs:
```
When the Multi-value or Include all value options are enabled, Grafana converts the labels from plain text to a regex compatible string. Which means you have to use =~ instead of =.
```

For some reason, the details dashboards seemed unaffected, but we should probably check and change them all to be safe against whatever the user happens to input

**Comment by keithf4** [comment]
PR https://github.com/CrunchyData/pgmonitor/pull/155 should fix this
