### ISSUE TITLE
linux and win paths in crunchy-prometheus.yml

### ISSUE THREAD

**Issue by hunleyd** [CrunchyData/pgmonitor#137]
instead of having two versions of this file, we should see if we can do:
```
- files:
   - CRUNCHYPATH\pgMonitor\config\prometheus\auto.d\*yml
   - /etc/prometheus/auto.d/*yml
```

**Comment by keithf4** [comment]
Good idea. Will add that in next version

**Comment by sharmay** [comment]
For now go with two files.

**Comment by keithf4** [comment]
Testing this out, we cannot do this as a single file with the CRUNCHYPATH variable as it's done now.
If you do this in the yaml file:
```
  - CRUNCHYPATH\pgMonitor\config\prometheus\auto.d\*.yml
  - CRUNCHYPATH\pgMonitor\config\prometheus\alert-rules.d\*.yml
```
when prometheus tries to load that, it prepends the default config location directory on it like this:
```
- /etc/prometheus/CRUNCHYPATH\pgMonitor\config\prometheus\alert-rules.d\*.yml
- /etc/prometheus/CRUNCHYPATH\pgMonitor\config\prometheus\auto.d\*.yml
```
