### ISSUE TITLE
Add quick links to other dashboards

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/pgmonitor#144]
For easier navigation, add links to other dashboards as shown in the below screenshot
![image](https://user-images.githubusercontent.com/36273111/70740272-691c4800-1cde-11ea-9565-0472bac2c164.png)

**Comment by keithf4** [comment]
See about doing this at the same time I do the general settings review since I'll be touching almost all dashboards at that time anyway - https://github.com/CrunchyData/pgmonitor/issues/145

**Comment by keithf4** [comment]
Likely not going to be adding this after further discussion. Having unrelated dashboards linked together makes it hard to design a way to exclude dashboards that some people aren't using (Ex people not using etcd, backrest or pg_stat_statement).
