### ISSUE TITLE
Review Grafana dashboard default settings

### ISSUE THREAD

**Issue by keithf4** [CrunchyData/pgmonitor#145]
Review all dashboards to ensure either a consistent or practical default for the timespan shown. 

Ex: 
- Details dashboards to 2 days
- Backrest Dashboard 2 weeks

Also check for general settings consistency.  Ex: Ensure they're not editable

**Comment by sharmay** [comment]
What about overview dashboard ?

|Dashboard|Duration|Refresh|
|--------------|------------|-----------|
|Overview|5m|30s|
|Details|2d|15m|

**Comment by keithf4** [comment]
I'm on board with the L1 and L2 durations. Not sure making L3 1 week really makes any sense tho. Any specific reason for that? Maybe just leave that at 2 days as well?

Only one that really seems like an outlier from the above pattern would be the pgbackrest dashboard. To me that one makes more sense to be set at 2 weeks since one of the most common backup patterns with it is weekly fulls/daily incrementals. And client's retention is usually at least that long as well.

**Comment by keithf4** [comment]
Addressed in PR https://github.com/CrunchyData/pgmonitor/pull/159

**Comment by keithf4** [comment]
PR #159 has been merged.
