### ISSUE TITLE
PGBackrest panel in PostgreSQL Details dashboard changing colors

### ISSUE THREAD

**Issue by keithf4** [CrunchyData/pgmonitor#146]
The background color for the pgbackrest panel in the PostgreSQL Details dashboard changes to red after just a short amount of time. This is because the background color option was turned on but no specific thresholds were set, so it's using defaults of 50,80.

Either turn background coloring off or find a value that will keep it a constant desirable color.

**Comment by sharmay** [comment]
What about overview dashboard ?

|Level|Dashboard | Duration | Refresh|
|--|-- | -- | --
L1|Overview | 5m | 30s
L2|Details | 2d | 15m
L2|More Details|w|1h

**Comment by keithf4** [comment]
PR https://github.com/CrunchyData/pgmonitor/pull/155 should fix this
