### ISSUE TITLE
Template variable regex grabs too much

### ISSUE THREAD

**Issue by cbandy** [CrunchyData/pgmonitor#147]
When deployed on Kubernetes (using Crunchy PostgreSQL Operator) I noticed strange values in the PGCluster dropdown on the PostgreSQL Details dashboard. I suspect it has to do with regex in the Variable definition.

Dashboard:
<img width="582" alt="Screen Shot 2019-12-19 at 5 01 53 PM" src="https://user-images.githubusercontent.com/106560/71282295-6a73f300-2324-11ea-9f26-5a6513f9811e.png">

Settings:
<img width="417" alt="Screen Shot 2019-12-20 at 9 42 03 AM" src="https://user-images.githubusercontent.com/106560/71283051-b0c95200-2324-11ea-9ca6-5fadadd29f89.png">

**Comment by keithf4** [comment]
PR https://github.com/CrunchyData/pgmonitor/pull/148 has been merged
