### ISSUE TITLE
Expose error log count to prometheus

### ISSUE THREAD

**Issue by keithf4** [CrunchyData/pgmonitor#15]
Idea from client to track the number of FATAL, ERROR, WARNING messages in the postgres logs and feed that to prometheus for alerting & trending.

This should be doable with a custom script to node_exporter. Will likely need some minimal info in the log_line_prefix and also an option/variable to the script to let it know what the prefix is.

**Comment by keithf4** [comment]
I believe we're going to go with tail_n_mail for real-time log monitoring for errors and pgbadger for log analysis if you want to close this issue.

**Comment by gregscds** [comment]
Delegating this to tail_n_mail instead seems more reasonable to me than stretching the node exporter to this task.  Closing this as part of decluttering old Issues we're unlikely to act on.
