### ISSUE TITLE
Service file not detecting invalid files in QUERY_FILE_LIST

### ISSUE THREAD

**Issue by sharmay** [CrunchyData/pgmonitor#162]
When QUERY_FILE_LIST includes a missing file, service doesn't detect it properly and still show success on start/restart

**Comment by hunleyd** [comment]
does the exporter successfully start and run and just skips the missing entry? or does fail in a way that the service manager doesn't notice it failed?

**Comment by keithf4** [comment]
Yeah, service may start ok and report that back to ansible. But could be throwing errors in logs. Automating something to ensure a good QUERY_FILE_LIST would be nice, but the exporters are pretty explicit when they don't start right. And if alert rules are in place, Prometheus should be throwing scrape errors as well.

If everything is running fine, though, that definitely cause for concern and shows a need for additional error detection in ansible.

**Comment by sharmay** [comment]
Verify that files listed in QUERY_FILE_LIST are present before starting service.
