### ISSUE TITLE
Service monitoring

### ISSUE THREAD

**Issue by sharmay** [CrunchyData/pgmonitor#167]
Add support to monitor service status and generate alert when service status check fails.
Ex: port check, service pid check etc

**Comment by keithf4** [comment]
If the exporter service isn't running, how would it throw an error?

If the exporter is experiencing errors, they already exporter scrape error counts that we have alerts for.

**Comment by sharmay** [comment]
> If the exporter service isn't running, how would it throw an error?
> 
> If the exporter is experiencing errors, they already exporter scrape error counts that we have alerts for.
> For postgres itself, it already exports the "up" metric to report the status of the DB server.

Good points and I understand but also thinking if pgbouncer is down we will not detect and not alert or if haproxy is down we will not detect and not alert or if grafana is down we will not detect and not alert etc, may be  
https://github.com/prometheus/blackbox_exporter
https://github.com/prometheus/blackbox_exporter/blob/master/example.yml

**Comment by keithf4** [comment]
That looks great! Provided by the prometheus devs too

**Comment by keithf4** [comment]
Already done:
 - Postgres - already done via pg_up in postgres exporter

Absence alerts:
  - Etcd
  - pgbouncer (with pgbouncer_fdw)
  - Future version of HAProxy with built in exporter
  - Patroni (with patroni exporter)

Blackbox
  - Patroni (without patroni exporter)
  - Current HA Proxy
     - Is HA Proxy up?
     - Is HAProxy able to communicate with it's targets?
  - Grafana
  - pgbouncer (without pgbouncer_fdw)

**Comment by keithf4** [comment]
Added in PR https://github.com/CrunchyData/pgmonitor/pull/176
