### ISSUE TITLE
Feature Request:  Add network graphs to default dashboard

### ISSUE THREAD

**Issue by youattd** [CrunchyData/pgmonitor#169]
Please add network monitor graphs to the default dashboard.
This will help correlate HA, Patroni, and kubernetes cluster issues with DB issues.

Some metrics that would be useful to monitor:

- tcp throughput (r/w)
- udp throughput (r/w)
- interface error rate, dropped packets, latency and liveness

Ping and ping times may be less useful, especially for VIPs, and ICMP is often blocked, but when available, worth monitoring.

Some starting example dashboards here:

- https://grafana.com/grafana/dashboards/1856

**Comment by keithf4** [comment]
Network Dashboard will be included in next release
