### ISSUE TITLE
Link error in documentation

### ISSUE THREAD

**Issue by PauloLaScience** [CrunchyData/pgmonitor#227]
On page [https://access.crunchydata.com/documentation/pgmonitor/latest/exporter/](https://access.crunchydata.com/documentation/pgmonitor/latest/exporter/) if you click next at the end of the page you get an "page not found" 
[https://access.crunchydata.com/documentation/prometheus/](https://access.crunchydata.com/documentation/prometheus/) This is the invalid url
[https://access.crunchydata.com/documentation/pgmonitor/latest/prometheus/](https://access.crunchydata.com/documentation/pgmonitor/latest/prometheus/) This is the correct one if you use the navigation bar
Kind regards
PaulemPG

**Comment by keithf4** [comment]
Looks like this link has been fixed. Can you confirm it's working for you as well?

**Comment by PauloLaScience** [comment]
Thanks, it's fixed.
