### ISSUE TITLE
Verify pgBackRest version is the same across cluster

### ISSUE THREAD

**Issue by pgguru** [CrunchyData/pgmonitor#228]
**Describe the enhancement you are proposing:**

Would be nice to have a check that verifies that the version of pgBackRest matches across the cluster.  Alerting on something would help identify if there'd been a `yum update` that modified the version on one of the hosts that then breaks archiving.

(Might be that we want to include version checking for other software versions/packages, but backrest is a high-priority one that has the potential to break clusters if it's different.)

**Comment by keithf4** [comment]
Started investigating this and the current issue is that we only gather and store backrest info from the primary system. So while we could catch backrest version differences on clusters running on different systems, we currently cannot detect a difference between versions on the replicas of a given cluster.

**Comment by keithf4** [comment]
Further testing on this, if one system gets backrest updated to a new version, or is different in any way from the main repo on a dedicated backup host setup, the `pgbackrest info` command that would return the version info will fail anyway. So will need some other way to evaluate the backrest version directly from the system itself, not using the `info command`.

**Comment by pgguru** [comment]
Are we guaranteed to have installed via packages?  It may be that the locking packages already take care of this issue now.

**Comment by keithf4** [comment]
I don't believe we have a lock for an individual version of backrest. Just a maximal version. 

Would be nice to be able to have this check in the general pgMonitor release as well, not just in HA. Seeing if I can figure something out.

**Comment by keithf4** [comment]
So I made a node_exporter textfile prom generator script to just output the pgbackrest version directly from the `pgbackrest version` binary call. This will also allow checking the version on the backrest repo host node where PG may not be installed.

**Comment by keithf4** [comment]
Still investigating this. The node_exporter prom file is a lot of extra setup to do (requires a separate cron just for it). May be able to make use of the file_fdw to run an external program.

**Comment by keithf4** [comment]
The version metric has been included for now but has limited functionality on doing this. With the TLS option now it play, the requirement for matching versions may not be as strict in the near future.
