### ISSUE TITLE
ccp_connection_stats_max_idle_in_txn_time metric is returning a negative value sometimes

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/pgmonitor#237]
**Describe the issue:**
ccp_connection_stats_max_idle_in_txn_time metric is returning a negative value sometimes.

Running the query repeatedly using the SQL used for the metric also returned negative value sometimes as shown below

postgres=# select coalesce(extract(epoch from (max(now() - state_change))),0) from pg_catalog.pg_stat_activity where state = 'idle in transaction';
 coalesce  
-----------
 -0.000691
(1 row)

**Describe the expected behavior:**
This value should not be negative.

Using clock_timestamp() instead of now() should fix this issue.

**Tell us about your environment:**  
- pgMonitor Version:
4.4
- PostgreSQL Version:  
13.2
- Operating System:  
RHEL 7
- Exporter in use:  
postgres-exporter
- Virtualization:  
- Any customization:

**Comment by keithf4** [comment]
PR has been created for this. Thanks for the report!

**Comment by keithf4** [comment]
This issue has been fixed for the next release of pgMonitor
