### ISSUE TITLE
Investigate pgbouncer exporter

### ISSUE THREAD

**Issue by keithf4** [CrunchyData/pgmonitor#251]
Using the pgbouncer_fdw to monitor pgbouncer means that there's only a single connection configuration possible. This means that if pgbouncer is running on a replica and readonly queries are being used there, there is no easy way to monitor the replica's pgbouncer.

Investigate using the pgbouncer exporter

**Comment by cbrianpace** [comment]
@andrewlecuyer

**Comment by keithf4** [comment]
Working on a possible solution to monitoring multiple pgbouncers with the pgbouncer_fdw

https://github.com/CrunchyData/pgbouncer_fdw/pull/13

**Comment by keithf4** [comment]
The PR for pgbouncer_fdw to support multiple targets and pgbouncer versions is ready for review for anyone that is keeping an eye on this issue.

https://github.com/CrunchyData/pgbouncer_fdw/pull/13

**Comment by keithf4** [comment]
pgBouncer_fdw 1.0 will be how we manage pgbouncer metric collection moving forward
