### ISSUE TITLE
Guide how to setup in existing prometheus grafana infra

### ISSUE THREAD

**Issue by giovannicandido** [CrunchyData/pgmonitor#262]
**Describe the enhancement you are proposing:**
Is great we can quick start a new prometheus and grafana setup with pgmonitor, but I would prefer to use a existing environment in order to have just one installation of the tools to minimize resource utilization.

For this, a guidance on how to setup a existing installation, would be appreciated. Like the one provided by the helm package [community prometheus](https://prometheus-community.github.io/helm-charts/) using the apis like *ServiceMonitor* to configure the scrap and grafana import dashbords available in the grafa.com site.

**Comment by keithf4** [comment]
Thank you for the suggestion! We'll see about adding something like that during the next documentation review.

**Comment by keithf4** [comment]
So each section of the documentation describes how to set things up from scratch, describing the purpose of each file and where they are installed. This can be used to incorporate any pieces of pgMonitor into an existing setup already. And setting up additional systems to monitor is really no different than setting up a single one. You just need to do the portions that are relevant to an individual database instance.

Is there something more specific you are looking for?

**Comment by giovannicandido** [comment]
Interesting, I will check the documentation more in deep and see how to recreate in a kubernetes cluster, with prometheus installed with prometheus operator.
I was thinking in how to recreate the examples in a already installed prometheus, then I saw only information about using package manages, systemd and as a consequence virtual machines, to provide the same functionality.
The kustomize example in the repository https://github.com/CrunchyData/postgres-operator-examples should be a good starting point for what I want to do.

**Comment by keithf4** [comment]
We will try and see about improving the documentation where we can. Thank you for the suggestion!
