### ISSUE TITLE
DB Exporter Scrape Errors

### ISSUE THREAD

**Issue by kyle-rf** [CrunchyData/pgmonitor#270]
**Describe the issue:**
Using the CrunchyData Postgres Operator.
After upgrade to 4.7.4
the exporter is logging the following errors:

**"Error running query on database "127.0.0.1:5432": ccp_pg_stat_statements_reset pq: function monitor.pg_stat_statements_reset_info(integer) does not exist"**

**"Error running query on database "127.0.0.1:5432": ccp_nodemx_data_disk pq: query-specified return tuple and function return type are not compatible"**

**Describe the expected behavior:**
There were no errors from the exporter on the previous version.

**Tell us about your environment:**  
- pgMonitor version:  Not Using pgMonitor
- Container or non-container:  Container
- Container name / image:  database / registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.5-4.7.4
- Operating System for non-container:  N/A
- PostgreSQL Version:  13.5
- Exporter(s) in use (incl. version):  exporter / registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:centos8-4.7.4
- Prometheus version:  quay.io/prometheus/prometheus:v2.27.1
- AlertManager version:  quay.io/prometheus/alertmanager:v0.22.0
- Grafana version:  grafana/grafana:8.0.5

**Comment by kyle-rf** [comment]
whoops, should have placed this in the postgres_exporter repo

**Comment by kyle-rf** [comment]
This issue can be closed.  Created the issue in the postgres_exporter repo: https://github.com/CrunchyData/postgres_exporter/issues/7

**Comment by keithf4** [comment]
Answered question on postgres_exporter repo.
