### ISSUE TITLE
haproxy metrics/dashboard

### ISSUE THREAD

**Issue by hunleyd** [CrunchyData/pgmonitor#277]
**Describe the enhancement you are proposing:**

Any plans to add a dashboard similar to https://grafana.com/grafana/dashboards/2428 to show what's going on with HAProxy as part of an HA cluster?

**Comment by keithf4** [comment]
Looking at other examples, there is a separate one for haproxy 2 even from the same author (https://grafana.com/grafana/dashboards/12693) . Need to see if there's any differences in the exporter between 1.x and 2.x

**Comment by hitech73** [comment]
This would be a great addition. I do have clients that have asked for this.

**Comment by hunleyd** [comment]
CS15 is wanting this, fyi

**Comment by jchancojr** [comment]
> CS15 is wanting this, fyi

https://github.com/rfmoz/grafana-dashboards/blob/master/prometheus/haproxy-2-full.json

**Comment by keithf4** [comment]
Looks like we're supporting haproxy 1.5 - 2.7 in Crunchy Postgres. However, it would be tricky to support dashboards for both versions right now. Any objects to the dashboard only being supported if using haproxy >= 2.x?

**Comment by jchancojr** [comment]
WFM. Eventually will be deprecated anyway

**Comment by keithf4** [comment]
Confirmed we will be looking into adding support for the HAProxy 2.x exporter and dashboard for the next release after 4.8.

**Comment by keithf4** [comment]
Noting here to try making a separate package for the haproxy grafana dashboard.

**Comment by cbrianpace** [comment]
Once the built in exporter has been packaged, I can assist with building Grafana dashboards if necessary.

**Comment by hunleyd** [comment]
OT104 wants this too
