### ISSUE TITLE
Usage of own created Grafana instead of using monitor stack

### ISSUE THREAD

**Issue by sambeet99** [CrunchyData/pgmonitor#280]
Is it possible to use our own grafana dashboard that is running in a different namespace instead of using PGO Monitor stack grafana ?

Explanation:-

I am running pgo and few pg clusters in my k8s . Also I have Grafana, prom , loki stack running in some different namespace. Now I want to enable metrics for my Pg clusters, so I need to add sidecar exporter container which is easily done.

But for Grafana dashboard I want to use my own Grafana instead of crunchydata monitor stack grafana. 
How to achieve this configuration ?

**Comment by cbandy** [comment]
@sambeet99 The Grafana dashboards for Kubernetes are available at https://github.com/CrunchyData/postgres-operator-examples/tree/main/kustomize/monitoring/dashboards. You can adjust, [import](https://grafana.com/docs/grafana/latest/dashboards/export-import/), or [provision](https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards) them as needed.

**Comment by keithf4** [comment]
Unless there are any further questions, will be closing this issue by the end of this week.

**Comment by todeb** [comment]
1. Any plans for adding possibility to installing just exporter and service monitor to integrate it with existing prometheus grafana and alertmanager?
2. I could not find exporter or /metrics endpoint, where is this?

**Comment by keithf4** [comment]
1. You can already just install specific components on an as needed basis. 

If you have specific questions about setting up monitoring with the operator, please check the documentation there (https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/monitoring/) or ask on their github (https://github.com/CrunchyData/postgres-operator)

2. The endpoint is available via an http interface. The port depends on which exporter you're accessing and can also be customized. You can reach it with either curl on the command line or via a web browser if you have access. Again, if these are specific issues with using the operator, please try asking on that repository.
