### ISSUE TITLE
OS Details dashboard, left Filesystem Usage panel does not show nfs fstype.

### ISSUE THREAD

**Issue by hitech73** [CrunchyData/pgmonitor#286]
In the OS Details dashboard, we have two panels for Filesystem Usage. 

The panel on the left is using a query with **fstype=~"xfs|ext[234]”**.  This restricts other fstype like nfs for example. This should be changed to **fstype!~".*tmpfs.*|.*root.*|.*pipe.*”** to match the one on the right. In the same query we are using **node_filesystem_avail_bytes** this should be changed to **node_filesystem_free_bytes** again to match the one on the right. 

- pgMonitor version:  4.5
- Container or non-container:  non-container
- Operating System for non-container:  RHEL8
- HA 1.12
- PostgreSQL Version:  14

**Comment by keithf4** [comment]
Merged for next release
