### ISSUE TITLE
Bug in postgres_exporter pgbouncer queries

### ISSUE THREAD

**Issue by wymangr** [CrunchyData/pgmonitor#288]
**Describe the issue:**
There is a bug in the following queries in queries_pgbouncer.yml:

ccp_pgbouncer_pools
ccp_pgbouncer_clients
ccp_pgbouncer_servers

By using "SELECT user", it's selecting the current user that's executing the query and not selecting the "user" column from the pgbouncer table. So for example, with the "ccp_pgbouncer_pools" if I'm using the user "monitoring" to run the postgres exporter, instead of showing all the pools, it's just showing the pools for the "monitoring" user. 

**Describe the expected behavior:**
Using the same example of "ccp_pgbouncer_pools" I would expect to see all the connection pools for each user, not just the pools for the user running postgres_exporter.

**Tell us about your environment:**  
- pgMonitor version:  4.5
- Container or non-container:  non-container
- Container name / image:  n/a
- Operating System for non-container:  Centos 7.9
- PostgreSQL Version:  psql (13.7)
- Exporter(s) in use (incl. version):  postgres_exporter, version 0.10.1 
- Prometheus version:  2.36.2
- AlertManager version:  0.24.0
- Grafana version:  9.0.2

**Comment by wymangr** [comment]
Created PR to fix this issue: https://github.com/CrunchyData/pgmonitor/pull/289

**Comment by keithf4** [comment]
Thanks for finding and fixing this!

**Comment by keithf4** [comment]
Merged for next release
