### ISSUE TITLE
Node Exporter Missing Mounts

### ISSUE THREAD

**Issue by wymangr** [CrunchyData/pgmonitor#309]
**Describe the issue:**
We have multiple mounts for postgres. We have one for our wal and one for our logs for example:

```
sdb                          8:16   0    8T  0 disk
└─VPStorage-pgsql          253:6    0    8T  0 lvm  /var/lib/pgsql
sdc                          8:32   0  256G  0 disk
└─pgsql_wal-lv_wal         253:7    0  256G  0 lvm  /var/lib/pgsql/13/database/wal
sdd                          8:48   0  256G  0 disk
└─pgsql_logs-lv_log        253:8    0  256G  0 lvm  /var/lib/pgsql/13/database/log
sde                          8:64   0    8G  0 disk
└─etcdvg-lv_etcd           253:9    0    8G  0 lvm  /var/lib/etcd
sdf                          8:80   0    8T  0 disk
└─pgsql_archive-lv_archive 253:10   0    8T  0 lvm  /var/lib/pgsql/13/database/archive
```

Because the ccp_monitoring user doesn't have access (only the postgres user does) beyond /var/lib, the only disks it reports on are /var/lib/pgsql and /var/lib/etcd. 

It does NOT create a metric for:
/var/lib/pgsql/13/database/wal
/var/lib/pgsql/13/database/log
/var/lib/pgsql/13/database/archive

I did confirm that if you change the user in `/etc/systemd/system/node_exporter.service.d/crunchy-node-exporter-service.conf` to `User=root` it works as expected.

**Describe the expected behavior:**
I would expect all the disks on the server to be monitored

**Tell us about your environment:**  
- pgMonitor version:  
pgmonitor-pg-common.noarch       4.5-0Crunchy.el7.centos      installed
pgmonitor-pg13-extras.noarch     4.5-0Crunchy.el7.centos      installed

- Container or non-container:   non-container
- Container name / image:  n/a
- Operating System for non-container:  CentOS Linux 7 
- PostgreSQL Version:  psql (PostgreSQL) 13.7
- Exporter(s) in use (incl. version): node_exporter, version 1.3.1
- Prometheus version:  2.36.2
- AlertManager version:  0.24.0
- Grafana version:  v9.1.6

**Comment by keithf4** [comment]
Thanks for the report. We're looking into this to see if there are any permission changes that can be done or if we'll need to change to running this as root.

**Comment by keithf4** [comment]
Haven't had a chance to test this yet, but are you able to add the monitoring user to the database system group then set the mountpoint/folders to g+rx? We'll try and test that when we have a chance ourselves as well.

**Comment by wymangr** [comment]
@keithf4 

This is how the permissions currently look:

/var/lib/pgsql/13/database/
```
drwxr-xr-x.  7 postgres postgres   92 Nov 13 19:23 .
drwx------.  5 postgres postgres   95 Nov 13 21:15 ..
drwx------.  3 postgres postgres   29 Nov 13 19:26 archive
drwx------. 19 postgres postgres 4.0K Nov 17 05:00 data
drwxr-xr-x.  3 postgres postgres   17 Jul 19 06:56 log
drwxr-x---.  3 postgres postgres   29 Jul 19 06:56 spool
drwxr-xr-x.  3 postgres postgres   20 Jul 19 02:42 wal
```

pgmonitor was setup on our cluster using Crunchy's Ansible playbooks (don't know if this matters), and the user node_exporter was set to run as was `ccp_monitoring`. 

Does Postgres care what the permissions are of the directories it writes to? Or as long as the postgres user can write to it, it can be 777 for all it cares? The only server I have to test with is Production, so I don't want to break anything. 

What group do you mean when you say "database system" group? I'm assuming node_exporter only needs read access to the mounts? Maybe just adding the `ccp_monitoring` user to the postgres group and making sure the permissions are at least 740 should work? I know you don't really have control over users custom mounts, maybe it would just be better to run it as root to make sure everything is always being monitored?

**Comment by keithf4** [comment]
You cannot do 777. 

I found this discussion - https://groups.google.com/g/prometheus-users/c/1LvgwyAPx3U

It looks like the minimum node_exporter needs to check the size is the execute permission on the folder. So, I'd say 750 would be good. That thread talks about changing the permissions, but I never see him test the combination of group permissions and membership in the postgres group.

**Comment by keithf4** [comment]
By database system group, I just mean the group that the postgres system user is a member of. Default this is `postgres:postgres`.

We'd prefer not to run as root if at all possible. We're still investigating.

**Comment by wymangr** [comment]
I was finally able to do some testing on this.

This is what I did:

Original Disks and permissions
```
sdc                          8:32   0    8T  0 disk
└─VPStorage-pgsql          253:4    0    8T  0 lvm  /var/lib/pgsql
sdd                          8:48   0  128G  0 disk
└─pgsql_wal-lv_wal         253:3    0  128G  0 lvm  /var/lib/pgsql/13/database/wal
sde                          8:64   0  256G  0 disk
└─pgsql_logs-lv_log        253:2    0  256G  0 lvm  /var/lib/pgsql/13/database/log
sdf                          8:80   0    8G  0 disk
└─etcdvg-lv_etcd           253:1    0    8G  0 lvm  /var/lib/etcd
sdg                          8:96   0    8T  0 disk
└─pgsql_archive-lv_archive 253:0    0    8T  0 lvm  /var/lib/pgsql/13/database/archive

# ls -lah /var/lib/pgsql/13/database
total 4.0K
drwxr-xr-x.  7 postgres postgres   92 Nov 17 19:39 .
drwx------.  5 postgres postgres   95 Nov 13 05:35 ..
drwxr-xr-x.  2 postgres postgres    6 Nov 17 19:38 archive
drwx------. 19 postgres postgres 4.0K Nov 25 05:00 data
drwxr-xr-x.  3 postgres postgres   17 Jul 19 12:01 log
drwxr-x---.  3 postgres postgres   29 Jul 19 12:01 spool
drwxr-xr-x.  3 postgres postgres   20 Jul 19 02:42 wal
```

Metrics returned by node_exporter (missing `/var/lib/pgsql/13/database/wal`, `/var/lib/pgsql/13/database/log`, `/var/lib/pgsql/13/database/archive`)
```
node_filesystem_avail_bytes{device="/dev/mapper/VPStorage-pgsql",fstype="xfs",mountpoint="/var/lib/pgsql"} 7.44620126208e+11
node_filesystem_avail_bytes{device="/dev/mapper/etcdvg-lv_etcd",fstype="xfs",mountpoint="/var/lib/etcd"} 8.15429632e+09
node_filesystem_avail_bytes{device="/dev/mapper/rootvg-homelv",fstype="ext4",mountpoint="/home"} 9.50034432e+08
node_filesystem_avail_bytes{device="/dev/mapper/rootvg-optlv",fstype="ext4",mountpoint="/opt"} 1.914662912e+09
node_filesystem_avail_bytes{device="/dev/mapper/rootvg-rootlv",fstype="ext4",mountpoint="/"} 5.647589376e+09
node_filesystem_avail_bytes{device="/dev/mapper/rootvg-tmplv",fstype="ext4",mountpoint="/tmp"} 1.91561728e+09
node_filesystem_avail_bytes{device="/dev/mapper/rootvg-usrlv",fstype="ext4",mountpoint="/usr"} 7.998922752e+09
node_filesystem_avail_bytes{device="/dev/mapper/rootvg-varlv",fstype="ext4",mountpoint="/var"} 6.822662144e+09
node_filesystem_avail_bytes{device="/dev/sda1",fstype="ext4",mountpoint="/boot"} 8.51329024e+08
node_filesystem_avail_bytes{device="/dev/sda15",fstype="vfat",mountpoint="/boot/efi"} 5.06986496e+08
node_filesystem_avail_bytes{device="/dev/sdb1",fstype="ext4",mountpoint="/mnt/resource"} 1.50264639488e+11
node_filesystem_avail_bytes{device="tmpfs",fstype="tmpfs",mountpoint="/run"} 8.31041536e+09
node_filesystem_avail_bytes{device="tmpfs",fstype="tmpfs",mountpoint="/run/user/1910400001"} 1.665695744e+09
```

Added ccp_monitoring user to postgres group
```
usermod -a -G postgres ccp_monitoring
# id ccp_monitoring
uid=993(ccp_monitoring) gid=989(ccp_monitoring) groups=989(ccp_monitoring),26(postgres)
```

Restarted node_exporter and verified it was still missing the 3 mounts.

Changed permission of the 3 directories
```
chmod 750 /var/lib/pgsql/13/database/archive
chmod 750 /var/lib/pgsql/13/database/wal
chmod 750 /var/lib/pgsql/13/database/log
```

Restarted node_exporter and verified it was still missing the 3 mounts.

Changed permission on /var/lib/pgsql/13 as it was set to `drwx------.  5 postgres postgres   95 Nov 13 05:35 13`
```
chmod 750 /var/lib/pgsql/13/
```

Restarted node_exporter and verified it was still missing the 3 mounts.

Changed permission recursively to everything in the archive, wal and log directories.
```
chmod -R 750 /var/lib/pgsql/13/database/archive
chmod -R 750 /var/lib/pgsql/13/database/wal
chmod -R 750 /var/lib/pgsql/13/database/log
```

Restarted node_exporter and verified it was still missing the 3 mounts.

Changed permission to the /var/lib/pgsql/13/database directory
```
chmod 750 /var/lib/pgsql/13/database
```

Restarted node_exporter and verified it was still missing the 3 mounts.

Permissions are now set 750 all the way up through:
`drwxr-x---.  5 postgres postgres   95 Nov 13 05:35 13`
`drwxr-x---. 7 postgres postgres  92 Nov 17 19:39 database`
```
drwxr-x---.  2 postgres postgres    6 Nov 17 19:38 archive
drwxr-x---.  3 postgres postgres   17 Jul 19 12:01 log
drwxr-x---.  3 postgres postgres   20 Jul 19 02:42 wal
```

Updated the `User` in the service config file (`/etc/systemd/system/node_exporter.service.d/crunchy-node-exporter-service.conf`) to root, restarted node_exporter and verified that the 3 missing mounts are now there.

Let me know if there is anything else you would like me to try.

**Comment by wymangr** [comment]
Okay, I was able to get it to work with the ccp_monitoring user. I also had to change the permissions of `/var/lib/pgsql` to 750. So to recap, to get it to work I needed to:

1. add the ccp_monitoring user to the postgres group
2. change permissions of mounts (archive, log, wal) to 750
3. change permission of `/var/lib/pgsql/13` to 750
4. change permission of `/var/lib/pgsql` to 750
5. restart node exporter

My only worry, this fixes anything that the postgres group has permission to, but it will still miss custom mounts someone might have that's not related to postgres. It also makes me wonder if there are any other metrics not being captured.

**Comment by keithf4** [comment]
Thanks very much for looking into this and finding a solution! Always try and run things with least privileges possible, but wondering if maybe this service would be better as root. Will discuss with the team.

**Comment by wymangr** [comment]
Maybe, if we don't want to run it as root (understandable), it would be better off being configurable? Give the user an option to set the user/group in the service configuration via Ansible?

**Comment by keithf4** [comment]
Just following up on this, with Crunchy Postgres' provided ansible roles as of version 1.15, the user that runs the exporter services is configurable (`pgmonitor_os_user`, `pgmonitor_os_group`). It does not stop the creation of the default user by the packages that we provide and we're still working to see if that's may be possible in the future.

From the perspective of pgMonitor itself, I'm not sure there's much else that can be done for this issue. We'd prefer to not run as the root user by default, but the sysconfig file is fully configurable by anyone setting up pgMonitor outside of our provided packages and ansible roles.

**Comment by wymangr** [comment]
Sounds good. If there isn't anything else, feel free to close this out.
