### ISSUE TITLE
ccp_replication_lag_replay_time on master

### ISSUE THREAD

**Issue by zerkms** [CrunchyData/pgmonitor#319]
**Describe the issue:** sometimes during an intermittent short network hiccup exporter starts exporting replication lag-related metrics as if the pod is replica, not master (while it certainly is master).

Here is an example of a metric with corresponding labels

```
ccp_replication_lag_replay_time{deployment="db-db-j555", instance="10.51.7.155:9187", ip="10.51.7.155", job="crunchy-postgres-exporter", kubernetes_namespace="<redacted>", pg_cluster="<redacted>:db", pod="db-db-j555-0", role="master", server="localhost:5432"}
```

At the time of writing this message it had a constantly monotonously growing value (of over 1000 seconds), and both replicas had expected `0`.

I resolve it with just killing the pod.

**Describe the expected behavior:** exporter should more carefully watch the postgresql cluster node status.

**Tell us about your environment:**  
- pgMonitor version:  n/a
- Container or non-container:  container
- Container name / image:  `registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.3.0-0`
- Operating System for non-container:  ubuntu focal/jammy
- PostgreSQL Version:  14.6
- Exporter(s) in use (incl. version):  crunchydata operator
- Prometheus version:  n/a
- AlertManager version:  n/a
- Grafana version:  n/a

**Comment by keithf4** [comment]
Curious, do the `ccp_replication_lag_size_bytes` or `ccp_replication_lag_received_time` metric also start reporting any lag as well? Or just this metric? Can you double-check that those two metrics are actually even reporting anything at all. If the latter `_received_time` is not also reporting anything, that would be very odd and indicate it's something more in the communication between the exporter and Prometheus than the exporter itself (or a very old version of the exporter is running).

And is it just the pod with the exporter that you kill, or are you also doing any sorts of restarts/rebuilds on any of the database systems themselves when this happens?

Curious if you can look at the actual systems themselves and see what values are being reported by running the queries directly next time this happens. You can see the queries here:
https://github.com/CrunchyData/pgmonitor/blob/development/postgres_exporter/common/pg15/queries_general.yml#L50
https://github.com/CrunchyData/pgmonitor/blob/development/postgres_exporter/common/pg15/queries_general.yml#L68

@andrewlecuyer Have you seen this happening anywhere else before with the pods that run the exporters?

**Comment by andrewlecuyer** [comment]
@zerkms what do you see in the Pod logs for the primary when this occurs, e.g. is the HA system (Patroni) logging anything?

You mentioned that this occurs when there is a network issue, which means the instance might also be having trouble communicating with Kubernetes as needed to renew the leader key.  This, in turn, can cause Patroni to demote the instance, making it "read-only".

I am therefore wondering if something along those lines might be occurring here.

**Comment by zerkms** [comment]
Okay, it happened again (this time during 14.5 -> 14.6 rollout).

Answering to all your questions (I'm sorry I didn't do proper investigation prior the report):

> what do you see in the Pod logs for the primary when this occurs, e.g. is the HA system (Patroni) logging anything?

```
2023-01-24 20:30:25,283 INFO: no action. I am (db-db-lqkx-0), a secondary, and following a leader (db-db-8xhw-0)                                                                                                                                                                          
2023-01-24 20:30:32,952 INFO: no action. I am (db-db-lqkx-0), a secondary, and following a leader (db-db-8xhw-0)                                                                                                                                                                          
2023-01-24 20:30:43,015 INFO: no action. I am (db-db-lqkx-0), a secondary, and following a leader (db-db-8xhw-0)                                                                                                                                                                          
2023-01-24 20:30:52,972 INFO: no action. I am (db-db-lqkx-0), a secondary, and following a leader (db-db-8xhw-0)                                                                                                                                                                          
2023-01-24 20:31:02,441 INFO: no action. I am (db-db-lqkx-0), a secondary, and following a leader (db-db-8xhw-0)                                                                                                                                                                          
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:1052: InsecureRequestWarning: Unverified HTTPS request is being made to host 'db-db-f9tf-0.db-pods'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.ht
  InsecureRequestWarning,                                                                                                                                                                                                                                                                 
2023-01-24 20:31:05,041 INFO: Got response from db-db-f9tf-0 https://db-db-f9tf-0.db-pods:8008/patroni: {"state": "running", "postmaster_start_time": "2023-01-24 20:26:32.768802+00:00", "role": "replica", "server_version": 140006, "xlog": {"received_location": 69966364672, "replaye
2023-01-24 20:31:05,181 INFO: Cleaning up failover key after acquiring leader lock...                                                                                                                                                                                                     
server signaled                                                                                                                                                                                                                                                                           
2023-01-24 20:31:05,299 INFO: promoted self to leader by acquiring session lock                                                                                                                                                                                                           
server promoting                                                                                                                                                                                                                                                                          
2023-01-24 20:31:05,323 INFO: cleared rewind state after becoming the leader                                                                                                                                                                                                              
2023-01-24 20:31:06,468 INFO: no action. I am (db-db-lqkx-0), the leader with the lock                                                                                                                                                                                                    
2023-01-24 20:31:06,653 INFO: no action. I am (db-db-lqkx-0), the leader with the lock                                                                                                                                                                                                    
2023-01-24 20:31:17,084 INFO: Lock owner: db-db-lqkx-0; I am db-db-lqkx-0                                                                                                                                                                                                                 
2023-01-24 20:31:17,103 INFO: Assigning synchronous standby status to ['db-db-f9tf-0']                                                                                                                                                                                                    
server signaled                                                                                                                                                                                                                                                                           
2023-01-24 20:31:17,221 INFO: Synchronous standby status assigned to ['db-db-f9tf-0']                                                                                                                                                                                                     
2023-01-24 20:31:17,270 INFO: no action. I am (db-db-lqkx-0), the leader with the lock                                                                                                                                                                                                    
2023-01-24 20:31:27,154 INFO: no action. I am (db-db-lqkx-0), the leader with the lock                                                                                                                                                                                                    
2023-01-24 20:31:37,119 INFO: no action. I am (db-db-lqkx-0), the leader with the lock                                                                                                                                                                                                    
2023-01-24 20:31:47,181 INFO: no action. I am (db-db-lqkx-0), the leader with the lock                                                                                                                                                                                                    
2023-01-24 20:31:57,103 INFO: no action. I am (db-db-lqkx-0), the leader with the lock                                                                                                                                                                                                    
2023-01-24 20:32:07,194 INFO: no action. I am (db-db-lqkx-0), the leader with the lock                                                                                                                                                                                                    
2023-01-24 20:32:17,102 INFO: no action. I am (db-db-lqkx-0), the leader with the lock                                                                                                                                                                                                    
2023-01-24 20:32:27,120 INFO: no action. I am (db-db-lqkx-0), the leader with the lock                              
```

And then `db-db-lqkx-0` has a `master` role, acts as a master yet has a replication lag metric exported

> Curious, do the ccp_replication_lag_size_bytes or ccp_replication_lag_received_time metric also start reporting any lag as well?

These are the metrics from a pod with misbehaving exporter:

```
# TYPE ccp_replication_lag_size_bytes gauge
ccp_replication_lag_size_bytes{replica="10.31.0.144",replica_hostname="",replica_port="53868",server="localhost:5432"} 0
ccp_replication_lag_size_bytes{replica="10.31.2.195",replica_hostname="",replica_port="39438",server="localhost:5432"} 0

# TYPE ccp_replication_lag_received_time gauge
ccp_replication_lag_received_time{server="localhost:5432"} 1278

# TYPE ccp_replication_lag_received_time gauge
ccp_replication_lag_replay_time{server="localhost:5432"} 1278
```

> Curious if you can look at the actual systems themselves and see what values are being reported by running the queries directly next time this happens. You can see the queries here:

```
psql (14.6)
Type "help" for help.

postgres=# SELECT
postgres-#            CASE
postgres-#            WHEN pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn() THEN 0
postgres-#            ELSE EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
postgres-#            END
postgres-#         AS replay_time
postgres-#         , EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
postgres-#         AS received_time
postgres-# ;
 replay_time | received_time 
-------------+---------------
        1402 |          1402
(1 row)

postgres=# SELECT client_addr as replica
postgres-#         , client_hostname as replica_hostname
postgres-#         , client_port as replica_port
postgres-#         , pg_wal_lsn_diff(sent_lsn, replay_lsn) as bytes
postgres-#         FROM pg_catalog.pg_stat_replication
postgres-# ;
   replica   | replica_hostname | replica_port | bytes 
-------------+------------------+--------------+-------
 10.31.0.144 |                  |        53868 |     0
 10.31.2.195 |                  |        39438 |     0
(2 rows)

```

> And is it just the pod with the exporter that you kill, or are you also doing any sorts of restarts/rebuilds on any of the database systems themselves when this happens?

I just delete the current master pod and let kubernetes to reschedule it again somewhere else, more often than not it happens quick enough to start up and be re-elected as master again. But then it behaves fine.

I have just killed `db-db-lqkx-0` and within several seconds it was up and running, but this time another replica picked up the master role.

Now after restart if I run the first query on a new master it's this:

```
postgres=# SELECT
           CASE
           WHEN pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn() THEN 0
           ELSE EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
           END
        AS replay_time
        , EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
        AS received_time;
 replay_time | received_time 
-------------+---------------
           0 |           149
```

First column is constantly 0 and the second monotonously grows (but this db has almost no traffic, if any at all, so no clients read/write from it).

**Comment by keithf4** [comment]
Ok `ccp_replication_lag_received_time` is expected to always be increasing if there is no write traffic. It's watching for WAL files to be received and if a replica never receives any WAL files (because nothing writes to generate WAL), it will increase forever until it does. It should generally be zero all the time on a primary, though, too. We don't have any alerts set by default for it since it frequently causes false alarms, but it's a useful metric for diagnostic purposes like this.

The `replay` metric is looking at the difference between the last received and when it replayed the that. If the last received and last replayed WAL values are equal it stays at zero instead of increasing forever to avoid false positives on the alert, but can let you know when your replica isn't keeping up with primary WAL generation. 

It sounds like you're running into the issue that @andrewlecuyer is talking about. If it happens again, can you run that last query while the exporter is reporting a `replay_time` value? If the database itself is also reporting a value here, then it's not the exporter reporting erroneous data.

If you are having zero writes on that database, can you try doing some dummy writes and forcing a checkpoint before resetting things? Monitoring replay time can be a little weird sometimes on databases that have zero writes occurring since the replay is essentially monitoring for an event that is never happening. If you continue to see this issue on a busier database, then there could be some more cause for concern.

**Comment by zerkms** [comment]
> If it happens again, can you run that last query while the exporter is reporting a replay_time value? If the database itself is also reporting a value here, then it's not the exporter reporting erroneous data.

Isn't it there in my previous post already?

```
postgres=# SELECT
postgres-#            CASE
postgres-#            WHEN pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn() THEN 0
postgres-#            ELSE EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
postgres-#            END
postgres-#         AS replay_time
postgres-#         , EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
postgres-#         AS received_time
postgres-# ;
 replay_time | received_time 
-------------+---------------
        1402 |          1402
(1 row)
```

**Comment by zerkms** [comment]
Okay, during 14.5 -> 14.6 upgrade I have another cluster in the same state.

Queries from master:

```
postgres=# SELECT
postgres-#            CASE
postgres-#            WHEN pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn() THEN 0
postgres-#            ELSE EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
postgres-#            END
postgres-#         AS replay_time
postgres-#         , EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
postgres-#         AS received_time;
 replay_time | received_time 
-------------+---------------
        3859 |          3859
(1 row)

postgres=# select pg_last_wal_receive_lsn(), pg_last_wal_replay_lsn();
 pg_last_wal_receive_lsn | pg_last_wal_replay_lsn 
-------------------------+------------------------
 12A/50E80000            | 12A/51000000
(1 row)

postgres=# select pg_last_wal_receive_lsn(), pg_last_wal_replay_lsn();
 pg_last_wal_receive_lsn | pg_last_wal_replay_lsn 
-------------------------+------------------------
 12A/50E80000            | 12A/51000000
(1 row)

postgres=# SELECT pg_is_in_recovery()
postgres-# ;
 pg_is_in_recovery 
-------------------
 f
(1 row)
```

And from one of the replicas:

```
postgres=# select pg_last_wal_receive_lsn(), pg_last_wal_replay_lsn();
 pg_last_wal_receive_lsn | pg_last_wal_replay_lsn 
-------------------------+------------------------
 12A/60000000            | 12A/60000000
(1 row)

postgres=# select pg_last_wal_receive_lsn(), pg_last_wal_replay_lsn();
 pg_last_wal_receive_lsn | pg_last_wal_replay_lsn 
-------------------------+------------------------
 12A/60000000            | 12A/60000000
(1 row)

postgres=# SELECT pg_is_in_recovery();
 pg_is_in_recovery 
-------------------
 t
(1 row)

postgres=# SELECT
postgres-#            CASE
postgres-#            WHEN pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn() THEN 0
postgres-#            ELSE EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
postgres-#            END
postgres-#         AS replay_time
postgres-#         , EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
postgres-#         AS received_time
postgres-# ;
 replay_time | received_time 
-------------+---------------
           0 |           127
(1 row)
```

Shouldn't the `ccp_replication_lag` query use `pg_is_in_recovery()` in case condition instead of `pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn()`?

**Comment by keithf4** [comment]
So looks like it's not a problem with the exporter, it's just reporting what PG is returning. If you then perform any writes to that primary and/or perform a checkpoint, does that clear the state?

**Comment by keithf4** [comment]
Also just curious, just before this state is reached, has there just been a failover event? 

My current thoughts are that there is some network issue and a failover occurs. If your pod logs provided are for the primary in this state, then it does appear that may be what happened. That failover pushes the WAL replay forward on the new primary, but the received state is left where it was just before then. But since it's a primary, it's not going to be receiving WAL anymore so it doesn't clear. 

Discussing with coworkers to see if there's any issues around also adding the `pg_is_in_recovery()` state to the conditionals for both columns in this query. Thanks for the idea!

**Comment by zerkms** [comment]
> so it doesn't clear until some writes occur

It's totally not the case: I had observed it on a write-heavy databases too. I'm not a professional postgresql administrator, but I suspect it's the `ccp_replication_lag` that misuses `pg_last_wal_receive_lsn` and `pg_last_wal_replay_lsn` functions (or those functions are broken in postgresql 14.x).

**Comment by keithf4** [comment]
Can you at least confirm if the issue happens after a failover has occurred? Just trying to narrow down the cause because this is the first time I've seen this happen myself after using these metrics for quite a long time to monitor replication.

**Comment by zerkms** [comment]
It's not consistent: sometimes it happens, sometimes not. For 14.5 -> 14.6 it happened with higher chance, but most often failover happens fine too. So it's not after every failover.

> after using these metrics for quite a long time to monitor replication.

What expression do you use to trigger alert? Eg, does it not exclude `role=master` for instance?

**Comment by keithf4** [comment]
Looks like we don't have a default alert based on this metric at the moment, just the byte lag

https://github.com/CrunchyData/pgmonitor/blob/development/prometheus/common/alert-rules.d/crunchy-alert-rules-pg.yml.example#L206

There is no label for `role` in the metric at the moment, but that could be an interesting one to add vs putting it in the pg_is_in_recovery() state in the lag value itself. I have added an alert for it in the past, though, and simply gone on the value itself.

**Comment by keithf4** [comment]
So try replacing the `ccp_replication_lag` metric in your base queries file located here `/etc/postgres_exporter/##/queries_general.yml` (## being your major PG version). Then restart the global exporter.
```
ccp_replication_lag:
  query: "SELECT
           CASE
           WHEN pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn() THEN 0
           ELSE EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
           END
        AS replay_time
        , EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
        AS received_time
        , CASE
          WHEN pg_is_in_recovery() THEN 'replica'
          ELSE 'primary'
          END
        AS role"
  metrics:
    - replay_time:
        usage: "GAUGE"
        description: "Length of time since the last transaction was replayed on replica. Returns zero if last WAL recieved equals last WAL replayed. Avoids false positives when primary stops writing. Monitors for replicas that cannot keep up with primary WAL generation."
    - received_time:
        usage: "GAUGE"
        description: "Length of time since the last WAL file was received and replayed on replica. Always increases, possibly causing false positives if the primary stops writing. Monitors for replicas that stop receiving WAL all together."
    - role:
        usage: "LABEL"
        description: "Current role of target host. Values are either primary or replica"
```
That should give you a label in the metrics like this
```
ccp_replication_lag_replay_time{cluster_name="hotel", exp_type="pg", instance="192.168.122.16:9187", job="hotel_ip16_pg1", role="replica"}
ccp_replication_lag_replay_time{cluster_name="hotel", exp_type="pg", instance="192.168.122.36:9187", job="hotel_ip36_pg3", role="primary"}
```
And then I think you should be able to use a metric with this label in your lag alerts
```
expr: ccp_replication_lag_replay_time{role="replica"} > 12345
````

**Comment by zerkms** [comment]
`role` already is presented, it's added by the scraper I think. This is a metric I already have without changing anything:

```
ccp_replication_lag_replay_time{deployment="db-db-5hnc", instance="10.51.0.83:9187", ip="10.51.0.83", job="crunchy-postgres-exporter", kubernetes_namespace="<redacted>", pg_cluster="<redacted>", pod="db-db-5hnc-0", role="replica", server="localhost:5432"}
```

**Comment by keithf4** [comment]
Ok, that's something being added by the container system, it's not in base pgMonitor.

`pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn()` means that the state of the WAL that the replica received matches what has been replayed. So that system is caught up with replaying all of the WAL that it knows is in its queue to replay. It's a way to monitor if the replica is keeping up with the WAL generation of the primary. I believe this should always be zero on a primary, so I'm not sure why it's not that way for you. In fact, on a brand new primary before a failover has ever occurred, both of those values are null.

**Comment by zerkms** [comment]
Yep, I understand what it means - I'm just wondering why it's used as a criteria? `postgresql` documentat defines `pg_last_wal_receive_lsn` and `pg_last_wal_replay_lsn` really poorly for master replicas. Why it is used instead of `pg_is_in_recovery`?

**Comment by keithf4** [comment]
It's not being used to determine which is the master. It's being used to avoid false positives when monitoring replication from the replicas side when there are no writes on the primary. The other metric `ccp_replication_lag_received_time` does not use this condition and if you used it as an alerting metric, you'd often get false positives during times of low/zero writes. We still include it as a metric to at least have a way to monitor if the replica is receiving WAL from the primary, often setting it's threshold to something like 12+ hours.

My thinking was the same on there as well, but as soon as there's enough writes to cause another WAL to be generated on the master, I was thinking that it should reset that.

**Comment by keithf4** [comment]
So since you have that `role` label already, i think that would probably be the easiest way to solve things for you at this time. Just include that label in the alert rule to ensure it's only firing on the replicas like I showed above (with whatever value works for you)
```
expr: ccp_replication_lag_replay_time{role="replica"} > 12345
```
We'll investigate what we can do from the base pgMonitor metrics themselves and also look and see if maybe there is actually something wrong in the core code in PG here.

**Comment by keithf4** [comment]
Going to test this query out for the metric and see how it goes. If you're able to do the same, please let me know how it works for you
```
ccp_replication_lag:
  query: "SELECT
           CASE
           WHEN (pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn()) OR (pg_is_in_recovery() = false) THEN 0
           ELSE EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
           END
        AS replay_time
        ,  CASE
           WHEN pg_is_in_recovery() = false THEN 0
           ELSE EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
           END
        AS received_time
  metrics:
    - replay_time:
        usage: "GAUGE"
        description: "Length of time since the last transaction was replayed on replica. Returns zero if last WAL recieved equals last WAL replayed. Avoids false positives when primary stops writing. Monitors for replicas that cannot keep up with primary WAL generation."
    - received_time:
        usage: "GAUGE"
        description: "Length of time since the last WAL file was received and replayed on replica. Always increases, possibly causing false positives if the primary stops writing. Monitors for replicas that stop receiving WAL all together."
```

**Comment by zerkms** [comment]
And, during another failover it's here again.

The fix as expecting works:
```
postgres=# SELECT
           CASE
           WHEN (pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn()) OR (pg_is_in_recovery() = false) THEN 0
           ELSE EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
           END
        AS replay_time
        ,  CASE
           WHEN pg_is_in_recovery() = false THEN 0
           ELSE EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
           END
        AS received_time;
 replay_time | received_time 
-------------+---------------
           0 |             0
(1 row)
```

Other stats:

```
postgres=# SELECT
           CASE
           WHEN pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn() THEN 0
           ELSE EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
           END
        AS replay_time
        , EXTRACT (EPOCH FROM clock_timestamp() - pg_last_xact_replay_timestamp())::INTEGER
        AS received_time
;
 replay_time | received_time 
-------------+---------------
        3968 |          3968
(1 row)

postgres=# select pg_last_wal_receive_lsn(), pg_last_wal_receive_lsn();
 pg_last_wal_receive_lsn | pg_last_wal_receive_lsn 
-------------------------+-------------------------
 15E/15704000            | 15E/15704000
(1 row)

postgres=# select pg_is_in_recovery();
 pg_is_in_recovery 
-------------------
 f
(1 row)
```

Failover logs:

```
2023-01-29 20:50:05,257 INFO: no action. I am (db-db-64qb-0), a secondary, and following a leader (db-db-ndwz-0)
2023-01-29 20:50:15,316 INFO: no action. I am (db-db-64qb-0), a secondary, and following a leader (db-db-ndwz-0)
2023-01-29 20:50:25,337 INFO: no action. I am (db-db-64qb-0), a secondary, and following a leader (db-db-ndwz-0)
2023-01-29 20:50:32,603 WARNING: Request failed to db-db-ndwz-0: GET https://db-db-ndwz-0.db-pods:8008/patroni (HTTPSConnectionPool(host='db-db-ndwz-0.db-pods', port=8008): Max retries exceeded with url: /patroni (Caused by ReadTimeoutError("HTTPSConnectionPool(host='db-db-ndwz-0.db-pods', port=8008): Read timed out. (read timeout=2)",)))
server signaled
2023-01-29 20:50:32,823 INFO: promoted self to leader by acquiring session lock
server promoting
2023-01-29 20:50:32,861 INFO: cleared rewind state after becoming the leader
2023-01-29 20:50:32,858 INFO: Lock owner: db-db-64qb-0; I am db-db-64qb-0
2023-01-29 20:50:32,997 INFO: updated leader lock during promote
2023-01-29 20:50:37,373 INFO: no action. I am (db-db-64qb-0), the leader with the lock
2023-01-29 20:50:39,503 INFO: Lock owner: db-db-64qb-0; I am db-db-64qb-0
2023-01-29 20:50:39,530 INFO: Assigning synchronous standby status to ['db-db-8p9d-0']
server signaled
2023-01-29 20:50:39,604 INFO: Synchronous standby status assigned to ['db-db-8p9d-0']
2023-01-29 20:50:39,666 INFO: no action. I am (db-db-64qb-0), the leader with the lock
2023-01-29 20:50:50,331 INFO: no action. I am (db-db-64qb-0), the leader with the lock
2023-01-29 20:51:00,153 INFO: no action. I am (db-db-64qb-0), the leader with the lock
2023-01-29 20:51:10,018 INFO: no action. I am (db-db-64qb-0), the leader with the lock
```

**Comment by keithf4** [comment]
So actually going back and reading the docs again for the `pg_last_xact_replay_timestamp` function, it seems to be working as intended. Odd I've never run into this issue myself. But thanks for making the report and working with us to get a fix! Will include this in the next release of pgMonitor.

https://www.postgresql.org/docs/15/functions-admin.html
```
Returns the time stamp of the last transaction replayed during recovery. This is the time at which the commit or abort WAL record for that transaction was generated on the primary. If no transactions have been replayed during recovery, the function returns NULL. Otherwise, if recovery is still in progress this will increase monotonically. If recovery has completed then this will remain static at the time of the last transaction applied during recovery. When the server has been started normally without recovery, the function returns NULL.
```
