### ISSUE TITLE
Support "--auto-discover-databases" feature with postgres_exporter queries

### ISSUE THREAD

**Issue by kwould** [CrunchyData/pgmonitor#323]
**Describe the enhancement you are proposing:**
Postgres_exporter has a flag you can enable called `--auto-discover-databeses` where it allows you to dynamically run queries on the databases that are inside the postgres instance (https://github.com/prometheus-community/postgres_exporter#automatically-discover-databases). 
As a workaround to support these queries,  they need to be updated to utilize `current_database()` to add the extra label of which database the query is being ran on. It would be nice if given the current file structure we had `db specific` and `instance specific` queries so that it's easier to segment.

I'm happy to work on this, I just wanted to first see if this was something that would be worthwhile.

**Comment by keithf4** [comment]
I've seen quite a few open issues surrounding this auto-discovery feature so I've been avoiding it myself

https://github.com/prometheus-community/postgres_exporter/issues/588
https://github.com/prometheus-community/postgres_exporter/issues/753
https://github.com/prometheus-community/postgres_exporter/issues/750
https://github.com/prometheus-community/postgres_exporter/issues/735

**Comment by kwould** [comment]
Thanks for the quick response, @keithf4, anecdotally, most of those issues I saw due to having improperly configured queries. For my use case it would be sufficient enough if queries were segmented by files so that `db specific` queries lived in a seperate file compared to `instance specific` ones. This seems to fall with a similar pattern to how global queries are currently constructed. 
Would that break anything?

**Comment by keithf4** [comment]
Did this answer your question on using this feature? I don't think we'll be enabling that option by default in pgMonitor, but I think it should work for the per-db exporter if anyone wants to use it there.

**Comment by kwould** [comment]
@keithf4 thanks, yea this should be sufficient for us in the meantime
