### ISSUE TITLE
Grafana Dashboards - Error on Importing /grafana/common/PG_Details.json

### ISSUE THREAD

**Issue by localleon** [CrunchyData/pgmonitor#337]
**Describe the issue:**

The provided Dashbaords in the /grafana/ Folder don't work in the latest Version of Grafana! The import fails with "Failed to upgrade legacy queries Datasource PROMETHEUS was not found" 

Multiple used metrics like "ccp_connection_stats_total{cluster_name="[[pgcluster]]", job=~"[[pgnodes]]"}" have changed label names from e.g "cluster_name" to "pg_cluster". 

Is there a current version of this dashboard available that works with the v5 Operator? 

**Describe the expected behavior:**

Metrics should work out of the box when importing the Dashboard into Grafana 

**Tell us about your environment:**  
- pgMonitor version:   crunchydata/crunchy-postgres-exporter:ubi8-5.3.1-0
- Container or non-container:  Container
- PostgreSQL Version:  15
- Grafana version:  9.3.8

**Comment by dsessler7** [comment]
Hello @localleon,

When you say that it does not work with the latest version of Grafana, you seem to be implying that the way you used/installed these dashboards before worked with an earlier version of Grafana... Is that the case? What version of Grafana?

How are you installing the monitoring stack/dashboards? When using pgMonitor with Crunchy Postgres for Kubernetes (which I presume you are doing given your question about the v5 Operator), we recommend installing using the files found in the `postgres-operator-examples` repo. To do this, start with the docs found [here](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/monitoring/), which will help you get the exporter sidecar installed if it isn't already. At the bottom of that page there is a link that leads [here](https://access.crunchydata.com/documentation/postgres-operator/5.3.1/installation/monitoring/), which is where the documentation resides for installing the monitoring stack using the `postgres-operator-examples` repo.

**Comment by keithf4** [comment]
@localleon Were the doc links provided able to help you solve this issue?

**Comment by localleon** [comment]
Hey and sorry for the late response. 

I wanted to install the dashboards into my existing Monitoring Stack (Grafana), so we are collecting the metrics via a custom PodMonitor Resource into our Prometheus stack. 

The document links were sufficient, however I needed to resort to manualy editing the dashboard. You are not able to import the dashboards into newer versions of Grafana (above v9). I worked around that problem by just creating the standard datasource you used ("$PROMETHEUS") in my instance. Then I was able to import the dashboards and convert the Graphs to the new timeseries panels.

Maybe this needs to be more of a feature request/enhancement. I think it would be nice if the dashboards could be published separately, so users can import them into their own Grafana instance. I don't think the turn-key-monitoring solution provided by you is something people in enterprise settings would like to use? 

Hope this clarifies everything. 

Kind Regards, 
Leon

**Comment by keithf4** [comment]
We currently support using provisioning to add the dashboards, not importing via the GUI. We have tested provisioning them up until version 9.2 of Grafana without any issues.

I believe i've tried being able to support both provisioning and importing in the past with little luck. Maybe more recent versions are better at this now.

**Comment by localleon** [comment]
I think the problem only occures during importing when the hardcoded "PROMETHEUS"-Datasource is not available. Since you probaly provision both in the same step... the error never occures. 

I will try to get back to you with my version of the Dashboard which features the dynamic selection of a datasource. Maybe you are open for a PR here?

**Comment by keithf4** [comment]
So I do have to update the pgbouncer dashboard for some other changes that will be coming in pgMonitor 4.9. As part of that I'll be re-exporting that dashboard and doing so from Grafana 9.2. I'm wondering if that may fix this option of a legacy conversion that you're running into here. I'll try and have a PR up with that new dashboard either later today or early next week. Would you mind testing the import of that dashboard to see if that solves things?

Note that we will be making Grafana 9.2 the minimum required for pgMonitor 4.9 with me doing this new export. I do plan on re-exporting all the dashboards with 9.2 to convert them, but not sure that will make it in before the 4.9 release.

**Comment by keithf4** [comment]
So I have the new dashboard up now in this PR - https://github.com/CrunchyData/pgmonitor/pull/342

However, it does require that the new pgbouncer_fdw 1.0.0 is in place both in the database and with the new queries. I understand that you may not be able to fully test that at this time. But maybe at least see if you still get any errors about it not finding the datasource? Otherwise this may need to wait until we have pgMonitor 4.9.0 out to fully evaluate the solution.

**Comment by localleon** [comment]
Hey, 

i looked into the PR and i will not be able to test this issue because of your already mentioned reasons. I think reexporting the dashboards will fix the issue. You should probaly also switch the old "Graph"-Panel to the new "Timeseries"-Panel.

I think we could also solve my problem with something like this https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#add-a-data-source-variable

Adding a dynamic datasource-variable to all dashboards would allow you're current setup to still work and the dashboards would be reusable for customers who want to roll their own monitoring solutions.

**Comment by keithf4** [comment]
Apologies it took so long, but the next version of pgMonitor has added the datasource variable as you suggested. It will require version 5 for all of the metrics to properly work with these dashboards, but if you're able to get a chance to see if importing works better now I'd appreciate it.
