### ISSUE TITLE
(pg16) new metric: n_tup_newpage_upd

### ISSUE THREAD

**Issue by hunleyd** [CrunchyData/pgmonitor#339]
**Describe the enhancement you are proposing:**
> A new column has appeared in the pg_stat_*_tables family of statistical views: n_tup_newpage_upd. Together with the existing columns n_tup_hot_upd and n_tup_upd, it helps evaluate the effectiveness of HOT optimization.

> HOT optimization is done when updating non-indexed table columns. A new row version is created in the page, but no new records are created in the table indexes. This is the essence of HOT optimization. But in order for it to work, you need to have enough space in the page to place a new row version there. If the space is insufficient, the row version is created in another page and new entries are also created in all indexes. It is these row changes that are tracked by the new n_tup_newpage_upd counter.

> If the counter value is too high, you may want to consider reducing the fillfactor value for the table. By reserving more page space, you increase the chances for HOT optimization to work.

(from https://postgrespro.com/blog/pgsql/5970086)

**Comment by keithf4** [comment]
Added metric to pgmonitor-extension. Not adding new features into that until 1.0 for it is released, but PR is up

https://github.com/CrunchyData/pgmonitor-extension/pull/2

Once that's in, can look at adding a new panel to PG Details to track HOT vs non-HOT updates
