### ISSUE TITLE
Add support for postgres_exporter 13.0+

### ISSUE THREAD

**Issue by szelenka** [CrunchyData/pgmonitor#347]
**Describe the enhancement you are proposing:**
Consume the latest version from upstream for newest features and security patches. The upstream postgres_exporter introduced breaking changes, specifically to how `queries.yaml` is handled:
https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.13.0

Specifically these PRs:
https://github.com/prometheus-community/postgres_exporter/pull/801
https://github.com/prometheus-community/postgres_exporter/pull/811

This breaks the way `CrunchyData/pgmonitor` handles the dynamic generation of queries to export data to Prometheus in the `CrunchData/pgmonitor/postgres_exporter` folder.

The above PRs appear to be taking a strong-arm approach to force contributions to the upstream `prometheus-community/postgres_exporter` repo, rather than maintaining individual `queries.yaml` files.

To keep using the `prometheus-community/postgres_exporter` upstream, it seems this project will need to contribute back the changes to upstream.

**Comment by keithf4** [comment]
Yes we are tracking this and will find a solution for this project. For now, you can continue using a version of the postgres_exporter that supports the custom query file feature.

**Comment by keithf4** [comment]
We will be migrating to using the sql_exporter in the future to solve this issue - https://github.com/CrunchyData/pgmonitor/issues/395
