### ISSUE TITLE
(pg16) stale indexes

### ISSUE THREAD

**Issue by hunleyd** [CrunchyData/pgmonitor#358]
**Describe the enhancement you are proposing:**
Since pG16 now includes the last time an index scan happened for particular index, we could probably make a chart with two lines:
1. showing the count of indexes never scanned
2. showing the count of indexes not scanned in the past 6 months

Obviously the 6 months might best be user-configurable.

Reference query:
```
SELECT
	idxstat.schemaname as schema_name,
	idxstat.relname AS table_name,
	indexrelname AS index_name,
	idxstat.idx_scan AS index_scans_count,
    	idxstat.last_idx_scan AS last_idx_scan_timestamp,
	pg_size_pretty(pg_relation_size(idxstat.indexrelid)) AS index_size
FROM
	pg_stat_all_indexes AS idxstat
JOIN
    pg_index i ON idxstat.indexrelid = i.indexrelid
WHERE
    idxstat.schemaname not in ('pg_catalog','information_schema','pg_toast')
    AND NOT i.indisunique   -- is not a UNIQUE index
ORDER BY
	Idxstat.idx_scan ASC,
	Idxstat.last_idx_scan ASC;
```

**Comment by keithf4** [comment]
Will have to be VERY careful with this sort of metric. FK indexes often show up when checking on low index usage and removing those can have drastic consequences.

**Comment by keithf4** [comment]
This one seems a bit too much of a footgun to me as a general metric. I'd rather leave the analysis of unused index to an intentional investigation
