### ISSUE TITLE
monitoring of subtransactions

### ISSUE THREAD

**Issue by hunleyd** [CrunchyData/pgmonitor#359]
**Describe the enhancement you are proposing:**
Wondering if subtransactions should be monitored based on [this](https://bdrouvot.github.io/2023/07/30/rusting-a-new-postgres-c-extension-that-records-subtransactions-counters/) blog/extension and the reasoning therein

**Comment by keithf4** [comment]
Going to close this one for now. If it becomes a built-in metric can certainly revisit it.
