### ISSUE TITLE
Migrate deprecated grafana plugins

### ISSUE THREAD

**Issue by albundy83** [CrunchyData/pgmonitor#374]
Hello,

as you may know, angular plugins in Grafana have been deprecated, maybe it's time to migrate dashboards that use them ?
Here the reference link: https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

New plugins work correctly and you should not have any issue.

**Comment by keithf4** [comment]
Thank you for the notification, but I don't believe we're using any grafana plugins by default. At least I don't recall creating anything except dashboards for pgMonitor. Did any of our dashboards use plugins inherently that you saw?

**Comment by albundy83** [comment]
Sorry, I did not use the correct word, I mean "Visualizations", the commonly used "Graph" has been deprecated and replaced by "Time series".

**Comment by keithf4** [comment]
We're still using the 9.x series, so all of the graphs should be fine for now
When we migrate to 10.x we will definitely be testing that all dashboards are working as expected and update them accordingly.
Thank you!

**Comment by keithf4** [comment]
Closing this issue for now. If you continue to have any issues once pgMonitor supports Grafana 10.x, please feel free to re-open or create a new issue.
