### ISSUE TITLE
make use of pg_stat_monitoring

### ISSUE THREAD

**Issue by hunleyd** [CrunchyData/pgmonitor#385]
**Describe the enhancement you are proposing:**

Looking at [this](https://www.percona.com/blog/grafana-dashboards-implementing-the-postgresql-extension-pg_stat_monitor/) blog, it seems we might want to make use of some of the functionality that pg_stat_monitor includes

**Comment by keithf4** [comment]
Finally evaluating this. It's like pg_stat_statements on steroids. Does seem like it would cause additional shared memory usage, but no additional storage requirements that I can see.

Not sure I'd want this installed as default with pgMonitor, but it could be useful as an optional feature. If we tried to make a metrics file and dashboard for it, that would be another application we'd then kind of be responsible for keeping up to date to support. Maybe just make a note of it as a reference for additional query analysis for now?

**Comment by keithf4** [comment]
Noting in documentation
