### ISSUE TITLE
update copyright notices for 2024

### ISSUE THREAD

**Issue by youattd** [CrunchyData/pgmonitor#393]
**Describe the issue:**

Update copyright notice ranges to include 2024

**Describe the expected behavior:**

source code has updated copyright notices for 2024

**Tell us about your environment:**  
- pgMonitor version:  all
- Container or non-container:  both
- Container name / image:  all
- Operating System for non-container:  all
- PostgreSQL Version:  all
- Exporter(s) in use (incl. version):  all
- Prometheus version:  all
- AlertManager version:  all
- Grafana version:  all

**Comment by youattd** [comment]
pull request #392 392

**Comment by keithf4** [comment]
Done
