### ISSUE TITLE
Create a bgwriter drilldown dashboard

### ISSUE THREAD

**Issue by keithf4** [CrunchyData/pgmonitor#40]
Create a drill down dashboard from the Buffers graph on the PostgreSQLDetails that has graphs better split/arranged to get more useful information out. For example, checkpointing should be its own graph

**Comment by keithf4** [comment]
Will likely make this part of when https://github.com/CrunchyData/pgmonitor/issues/10 is resolved so it provides clearer details.

**Comment by gregscds** [comment]
It would be nice to do a large round of refactoring how pgmonitor looks at I/O at some point.  Until we're ready to do that, this one isn't an exciting individual step.  Closing.
