### ISSUE TITLE
pgbackrest-info.sh expectations on  --log-level-console

### ISSUE THREAD

**Issue by jpargudo** [CrunchyData/pgmonitor#401]
**Describe the issue:**

In https://github.com/CrunchyData/pgmonitor/blob/3d31a667b0a08f0aa6180655e1cc61a44867e6cc/postgres_exporter/linux/pgbackrest-info.sh ,

There's an expectation on the --log-level-console that is the default to "info".

But when used in an environment where that log-level is set somewhere to something else (eg. "debug"), then the output will add extra (debug or other) information, so the script returns wrong things.

A solution could be to enforce --log-level-console=info on any of the calls to "pgbackrest --output=json [...] info" ...  

**Describe the expected behavior:**

A working script whatever the level of verbosity set in --log-level-console

**Tell us about your environment:**  
- pgMonitor version: all  
- Container or non-container: both  
- Container name / image:  
- Operating System for non-container:  
- PostgreSQL Version:  all
- Exporter(s) in use (incl. version):  
- Prometheus version:  
- AlertManager version:  
- Grafana version:

**Comment by cbandy** [comment]
🤔 Does `--log-level-stderr=debug` have a similar negative effect?

**Comment by jpargudo** [comment]
@cbandy good catch! Given my tests, yes, it has the same similar negative effect...

Any program parsing the output of `pgbackrest --output=json [...] info` will have problems here too with that `--log-level-stderr=debug`...

So likely, `--log-level-stderr=info` has to be set here... too.

Thank you !

**Comment by keithf4** [comment]
Great catch! Thank you @cbandy

**Comment by cbandy** [comment]
Looking at the other [log options](https://pgbackrest.org/configuration.html#section-log), should we also set `log-level-file = off`? Would anyone want something there for scrapes?

**Comment by keithf4** [comment]
I would think that users would probably want all actions that backrest does logged there as they intend with their settings. Would also provide a place to look for more detailed info if something does go wrong with one of the script calls.

**Comment by keithf4** [comment]
pgBackRest's default for `--log-level-stderr` is actually `warn` so that's what I'm going to set it to here.
