### ISSUE TITLE
etcd dashboard using deprecated metrics

### ISSUE THREAD

**Issue by keithf4** [CrunchyData/pgmonitor#404]
**Describe the issue:**

The `etcd_debugging_mvcc_put_total` and `etcd_debugging_mvcc_delete_total` metrics have been deprecated and migrated to `etcd_mvcc_put_total` and `etcd_mvcc_delete_total` respectively. They were promoted out of being debug metrics in 3.5 https://etcd.io/docs/v3.4/upgrades/upgrade_3_5/

These are used for the key operations panel. Review the dashboard and see if anything else has been updated.

**Tell us about your environment:**  
- pgMonitor version:  4.11, 5.0-beta
- Container or non-container:  non-container
- Container name / image:  
- Operating System for non-container:  All
- PostgreSQL Version: N/A 
- Exporter(s) in use (incl. version):  N/A
- Prometheus version:  N/A
- AlertManager version:  N/A
- Grafana version:  N/A

**Comment by hunleyd** [comment]
you might want to peruse the [changelog](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md) for all the metric changes in 3.5 as there are a few. there's also a link to [this](https://etcd.io/docs/v3.5/metrics/) which shows all the metrics per version.
