### ISSUE TITLE
pgBackRest 2.52.1 breaks some backrest monitoring

### ISSUE THREAD

**Issue by keithf4** [CrunchyData/pgmonitor#420]
**Describe the issue:**

When monitoring pgBackRest version 2.52.1 (or any other version of backrest that has 3 digits in the version, but this is the only one so far), alerts will be raised for exporter scrape errors and in system logs. Also the pgBackRest grafana dashboard may also break since the informational metrics it uses are no longer available. Metrics for monitoring the backups themselves have not been affected by this issue, so alerting for failed backups should not be affected.

If users are on versions less than 2.52, this does not affect them. Upgrading to the latest version of pgBackRest 2.53 will also correct this issue.

sql_exporter
```
# HELP scrape_errors_total Total number of scrape errors per job, target, collector and query
# TYPE scrape_errors_total counter
scrape_errors_total{collector="crunchy_pgbackrest",job="global_targets",query="ccp_backrest_last_info",target="global"} 245
```
```
Jul 25 14:00:39 cd-dc1-pg2 sql_exporter[10651]: ts=2024-07-25T18:00:39.177Z caller=klog.go:134 level=error func=Errorf msg="Error gathering metrics: [from Gatherer #1] [job=global_targets,target=global,collector=crunchy_pgbackrest,query=ccp_backrest_last_info] sql: Scan error on column index 0, name \"backrest_repo_version\": converting driver.Value type string (\"2.52.1\") to a float64: invalid syntax"
```

postgres_exporter
```
Jul 25 14:41:19 cd-dc1-pg1 postgres_exporter[11231]: ts=2024-07-25T18:41:19.594Z caller=util.go:92 level=info msg="Could not parse string" err="strconv.ParseFloat: parsing \"2.52.1\": invalid syntax"
Jul 25 14:41:19 cd-dc1-pg1 postgres_exporter[11231]: ts=2024-07-25T18:41:19.594Z caller=namespace.go:241 level=info err="Unexpected error parsing column:  ccp_backrest_last_info backrest_repo_version 2.52.1\n"

```

**Describe the expected behavior:**

Should be able to handle any version of pgBackRest.

If users currently are not on version 2.52, we recommend waiting to upgrade. If you have upgraded to 2.52.1, please upgrade to 2.53 when it is available. This will be fixed in the next release of pgMonitor for postgres_exporter. For sql_exporter, this will be fixed in the `pgmonitor-extension` version 1.0.1, so no update to pgMonitor will be required.

**Tell us about your environment:**  
- pgMonitor version:  5.0 and older
- Container or non-container:  
- Container name / image:  
- Operating System for non-container:  
- PostgreSQL Version:  N/A
- Exporter(s) in use (incl. version):  postgres, sql
- Prometheus version:  Any
- AlertManager version:  Any
- Grafana version:  Any

**Comment by xakraz** [comment]
Hello @keithf4 👋🏻 

Sorry for reviving the topic that many months later 😅 

We are using the Crunchy PGO and we are facing the current error.
* We have updated the pgbackrest container image from `crunchydata/crunchy-pgbackrest:ubi8-2.51-1` -> `ubi8-2.53.1-1` without success
* We have updated the postgres exporter from `0.15.0-7` -> `0.16.0-1` without success either.

What should we do?

Don't hesitate to redirect me to the proper repository if needed 😁 

PS: I haven't had time to digg better but:
* I have manually triggered a full-backup using the `crunchy-pgbackrest:ubi8-2.53.1-1`
* BUT, in the DB, it still reported `2.52.1` 🤔 

```
...
      {
        "lsn": {
          "stop": "339/95001600",
          "start": "339/94000028"
        },
        "info": {
          "size": 40203159,
          "delta": 40203159,
          "repository": {
            "size": 5096762,
            "delta": 5096762
          }
        },
        "type": "full",
        "error": false,
        "label": "20250317-142058F",
        "prior": null,
        "archive": {
          "stop": "000000030000033900000095",
          "start": "000000030000033900000094"
        },
        "backrest": {
          "format": 5,
          "version": "2.52.1"   <----
        },
        "database": {
          "id": 4,
          "repo-key": 1
        },
        "reference": null,
        "timestamp": {
          "stop": 1742221308,
          "start": 1742221258
        }
      }
    ],
    "cipher": "none",
    "status": {
      "code": 0,
      "lock": {
        "backup": {
          "held": false
        }
      },
      "message": "ok"
    },
    "archive": [
      {
        "id": "16-4",
        "max": "000000060000033A0000000A",
        "min": "00000002000002E7000000BE",
        "database": {
          "id": 4,
          "repo-key": 1
        }
      }
    ]
  }
]

```

**Comment by keithf4** [comment]
@andrewlecuyer Has the fix for this been pushed into CPK?

**Comment by andrewlecuyer** [comment]
@xakraz the fix for this issue should be available in the latest releases of Crunchy Postgres for Kubernetes.  For instance, I confirmed that the fix is available in both CPK v5.7.4 and CPK v5.6.6.

I therefore recommend upgrading to the latest release of CPK to ensure you have the proper version of pgMonitor installed.  And once you have upgraded, I also recommend removing the `spec.monitoring` section from your spec, and then adding it back, to ensure any pgMonitor fixes and updates are properly applied to your database.

**Comment by xakraz** [comment]
Thanks @andrewlecuyer 🙏🏻 
I was just able to upgrade to v5.7.4 today and everything went well and my issue has been fixed!

**Comment by keithf4** [comment]
Thanks for letting us know!
