### ISSUE TITLE
Backport etcd 3.5 dashboard fix to 4.x line

### ISSUE THREAD

**Issue by keithf4** [CrunchyData/pgmonitor#441]
**Describe the issue:**

The grafana dashboard was fixed in pgMonitor 5.1 for metric name changes in etcd 3.5. Backport this to the 4.x line since 4.x now supports Grafana 10 as well.

**Tell us about your environment:**  
- pgMonitor version:  4.11
- Container or non-container:  
- Container name / image:  
- Operating System for non-container:  
- PostgreSQL Version:  
- Exporter(s) in use (incl. version):  
- Prometheus version:  
- AlertManager version:  
- Grafana version:

**Comment by hunleyd** [comment]
the PR didn't auto-close this for some reason, so closing manually
