### ISSUE TITLE
`/usr/bin/` vs `/bin/`

### ISSUE THREAD

**Issue by jkatz** [CrunchyData/pgmonitor#45]
In:

https://github.com/CrunchyData/pgmonitor/tree/master/exporter#installation-rhelcentos-7

it says:

```All executables are expected to be in /usr/bin```

However, as the `ccp_monitoring` user, I run `which`:

```-bash-4.2$ which ccp_pg_isready10.sh
/bin/ccp_pg_isready10.sh```

**Comment by sharmay** [comment]
On newer rpm based distribution /bin is symlink for /usr/bin which makes this executable available in both paths.
