### ISSUE TITLE
"Failed to execute operation: No such file or directory" trying to systemctl enable prometheus

### ISSUE THREAD

**Issue by dtseiler** [CrunchyData/pgmonitor#58]
I've been following the instructions at https://github.com/CrunchyData/pgmonitor/blob/master/prometheus/README.md to try to set up prometheus and alertmanager as the first step in installing pgmonitor. I downloaded prometheus-2.2.1 and alertmanager-0.14.0 tarballs from their download page linked from your README. I copied the executables contained in them to /usr/bin to match what is in the config files you provided.

After following the other instructions, I'm not able to enable the service:

```
$ sudo systemctl enable prometheus
Failed to execute operation: No such file or directory
```

I don't have any .service file for prometheus (or alertmanager), nor do I see any mention of one in your README.md. I've triple-checked for anything I might have missed but everything else checks out with copying files into place.

**Comment by hunleyd** [comment]
I was trying to help Don via Slack, and there is no `.service` file in our repo or in the prometheus download package. I suppose we could hand-craft one, but shouldn't there be one in our repo? I'm sure we ship in our Crunchy rpms and it seems like maybe that should be in the repo?

**Comment by keithf4** [comment]
There are rpm's out there that we base our own on that provide the base service files. I'll see if I can find them

**Comment by keithf4** [comment]
We based our RPMs off the ones maintained here

https://github.com/lest/prometheus-rpm

There are instructions for adding their repo and installing them. I'll see about updating our README to include this. Thanks for pointing it out!

**Comment by dtseiler** [comment]
Is that really safe to use? It isn't the prometheus team putting that out.

**Comment by dtseiler** [comment]
Based on that site, I got it working from the tar.gz. Just a few more notes for your master/prometheus/README.md. I suppose I could file them as a pull request for that file but here are my notes so far:

1. After downloading the prometheus and alertmanager tarballs, explain that the executables need to be copied to /usr/bin, and that the prometheus' console_libraries and console directories need to be copied to /usr/share/prometheus (also this dir needs to be created)

1. Need to create .service files for prometheus and alertmanager. I'd suggest creating them in your repo like you do with all the other .conf files. The .service files provided in that rpm repo work, with the one change to the alertmanager.service storage.path to use /var/lib/ccp_monitoring instead of /var/lib/prometheus

Let me know if you want me to try a change and PR myself.

**Comment by keithf4** [comment]
The source of the spec files are available for inspection to see what they are doing. And they are also pulling the actual code itself from the prometheus team. Until prometheus actually provides an rpm package themselves, this repository seems to work well.

I think pointing people to use this repo will solve the two issues you raised since it places the binary files and creates the necessary service files. Or if people don't want to use the packages, the service file provided at that repository can be used.

Thanks for pointing all this out!

**Comment by dtseiler** [comment]
I don't mean to be *too* paranoid, but there's no guarantee that the .spec files in their repo are what was used to build the RPM. I'm not saying that guy would do it, but perhaps some malicious agent is able to hack an RPM into place there. Let me know if I'm being crazy.

Anyway, in addition to my notes above, I would add to make sure that you open port 9090 (default prometheus web UI port) in your firewall (if you have one).

**Comment by dtseiler** [comment]
Didn't mean to close it
