### ISSUE TITLE
Decide on release numbering or naming plan

### ISSUE THREAD

**Issue by gregscds** [CrunchyData/pgmonitor#6]
The initial release of this project is being considered a V1.0 of some sort.  But there's not a clear plan for how version numbers are going to be assigned and advanced moving forward.  Crunchy projects used to default to the PostgreSQL version number model.  That scheme has changed in PostgreSQL V10 though, and it's not clear yet whether this project should follow the old PG numbering, the new PG numbering, or some other progression.

I especially wanted to get some input from our packaging team about how the PostgreSQL V10 RPM packaging work compared to the older versions.  If they have a strong preference for one style or the other after packaging both, my gut feel would be to follow that advice.

**Comment by keithf4** [comment]
I've worked with the build team and we're going with the same versioning convention as PG10. See the CHANGELOG so far.
